### Datenbasis für die Modellvalidierung

In [1]:
import pandas as pd
from IPython.display import display

In [ ]:
path_Bearbeitungscenter= r"C:\Users\fgottardo\OneDrive - Phoenix Mecano AG (Prod)\Bachelor Arbeit\Bachelor Arbeit\DAG\Validation Daten\Bearbeitungscenter_2.xlsx"   #Datenquelle BDE
path_FA = r"C:\Users\fgottardo\OneDrive - Phoenix Mecano AG (Prod)\Bachelor Arbeit\Bachelor Arbeit\DAG\Validation Daten\BeendeteFAs.xlsx"                           #Datenquelle ERP

#### Anzeigen von Header BDE Daten

In [ ]:

df_Bearbeitungscenter = pd.read_excel(path_Bearbeitungscenter)
display(df_Bearbeitungscenter.head(0))

Empty DataFrame
Columns: [Key, Machine - Workcenter, WorkCenter, WorkCenter Name, Artikel No, Artikel Beschr., Finished Quantity, OperationNo, EntryDate, Vorgänger Machine - Workcenter, Vorgänger WorkCenter, Vorgänger WorkCenter Name, Vorgänger OperationNo, Vorgänger EntryDate, Durchlauf Zeit (h), Durchlauf Zeit (t), Setup And Runtime Zeit (h), Setup Zeit(h), Run Zeit(h)]
Index: []

#### Bereinigen BDE Daten

In [ ]:
df_Bearbeitungscenter.drop(columns=['Machine - Workcenter', 'WorkCenter', 'WorkCenter Name', 'Artikel No', 'Artikel Beschr.', 'Finished Quantity', 'Vorgänger Machine - Workcenter', 'Vorgänger WorkCenter', 'Vorgänger WorkCenter Name', 'Vorgänger OperationNo', 'Vorgänger EntryDate' ], inplace=True)
display(df_Bearbeitungscenter.head(0))

Empty DataFrame
Columns: [Key, OperationNo, EntryDate, Durchlauf Zeit (h), Durchlauf Zeit (t), Setup And Runtime Zeit (h), Setup Zeit(h), Run Zeit(h)]
Index: []

#### Bereinigte Ansicht der BDE Daten

In [ ]:
df_Bearbeitungscenter['Key'] = df_Bearbeitungscenter['Key'].str.split('_').str[0]
display(df_Bearbeitungscenter.head(5))

,Key,OperationNo,EntryDate,Durchlauf Zeit (h),Durchlauf Zeit (t),Setup And Runtime Zeit (h),Setup Zeit(h),Run Zeit(h)
0,FA1124364,20,2025-05-13 17:08:06,272.00,34.00,1.93,1.62,0.32
1,FA1119513,21,2025-01-22 07:21:28,265.36,33.17,0.87,0.52,0.35
2,FA1125124,22,2025-05-20 09:21:44,200.33,25.04,27.75,0.30,27.45
3,FA1121718,20,2025-01-17 07:02:59,178.52,22.32,0.97,0.35,0.62
4,FA1116234,40,2024-07-24 16:23:26,170.56,21.32,4.18,0.73,3.45

#### Anzeigen von Header ERP Daten

In [ ]:
df_FA = pd.read_excel(path_FA, skiprows=2)
display(df_FA.head(0))

Empty DataFrame
Columns: [Nr., Beschreibung, Herkunftsnr., Arbeitsplannr., Menge, Startdatum, Enddatum, Fälligkeitsdatum, Zugewiesene Benutzer-ID, Status, Suchbegriff, Sales Order No., Customer Name, Fertigstellungsdatum]
Index: []

#### Bereinigen ERP Daten

In [ ]:
df_FA.drop(columns=['Beschreibung', 'Herkunftsnr.', 'Arbeitsplannr.', 'Zugewiesene Benutzer-ID', 'Status', 'Suchbegriff', 'Sales Order No.', 'Customer Name'], inplace=True)
display(df_FA.head(0))

Empty DataFrame
Columns: [Nr., Menge, Startdatum, Enddatum, Fälligkeitsdatum, Fertigstellungsdatum]
Index: []

#### inner join und Ansicht des Datenset

In [ ]:
df_merged = pd.merge(df_FA, df_Bearbeitungscenter, left_on='Nr.', right_on='Key', how='inner')
display(df_merged.head(5))

,Nr.,Menge,Startdatum,Enddatum,Fälligkeitsdatum,Fertigstellungsdatum,Key,OperationNo,EntryDate,Durchlauf Zeit (h),Durchlauf Zeit (t),Setup And Runtime Zeit (h),Setup Zeit(h),Run Zeit(h)
0,FA1112305,21,2024-06-12,2024-06-21,2024-06-21,2024-06-26,FA1112305,15,2024-06-13 14:49:01,117.59,14.70,17.12,0.45,16.67
1,FA1114090,300,2024-05-17,2024-05-30,2024-05-30,2024-05-31,FA1114090,70,2024-05-30 11:29:25,0.01,0.00,0.03,0.02,0.02
2,FA1114511,36,2024-05-16,2024-05-29,2024-05-29,2024-05-29,FA1114511,90,2024-05-28 11:59:28,0.00,0.00,3.07,0.33,2.73
3,FA1114659,50,2024-05-06,2024-05-31,2024-05-31,2024-05-31,FA1114659,50,2024-05-29 14:05:46,8.48,1.06,6.85,1.88,4.97
4,FA1114659,50,2024-05-06,2024-05-31,2024-05-31,2024-05-31,FA1114659,60,2024-05-29 14:06:41,0.02,0.00,0.00,0.00,0.00

In [9]:
df_merged.drop(columns=['Key'], inplace=True)
display(df_merged.head(0))

Empty DataFrame
Columns: [Nr., Menge, Startdatum, Enddatum, Fälligkeitsdatum, Fertigstellungsdatum, OperationNo, EntryDate, Durchlauf Zeit (h), Durchlauf Zeit (t), Setup And Runtime Zeit (h), Setup Zeit(h), Run Zeit(h)]
Index: []

#### Umbenenen der Spaltennamen

In [ ]:
df_merged.rename(columns={
    'Nr.' : 'FANummer',
    'Menge' : 'Menge',
    'Startdatum' : 'Startdatum',
    'Enddatum' : 'Enddatum',
    'Fälligkeitsdatum' : 'Fälligkeitsdatum',
    'Fertigstellungsdatum' : 'Fertigstellungsdatum',
    'OperationNo' : 'OperationNo',
    'EntryDate' : 'Logdatum',
    'Durchlauf Zeit (h)' : 'DurchlaufszeitIst(h)',
    'Durchlauf Zeit (t)' : 'DurchlaufszeitIst(t)',
    'Setup And Runtime Zeit (h)' : 'Rüst-Bearbeitungszeit(h)',
    'Setup Zeit(h)' : 'Rüstzeit(h)',
    'Run Zeit(h)' : 'Bearbeitungszeit(h)'
}, inplace=True)

display(df_merged.head(10))

,FANummer,Menge,Startdatum,Enddatum,Fälligkeitsdatum,Fertigstellungsdatum,OperationNo,Logdatum,DurchlaufszeitIst(h),DurchlaufszeitIst(t),Rüst-Bearbeitungszeit(h),Rüstzeit(h),Bearbeitungszeit(h)
0,FA1112305,21,2024-06-12,2024-06-21,2024-06-21,2024-06-26,15,2024-06-13 14:49:01,117.59,14.70,17.12,0.45,16.67
1,FA1114090,300,2024-05-17,2024-05-30,2024-05-30,2024-05-31,70,2024-05-30 11:29:25,0.01,0.00,0.03,0.02,0.02
2,FA1114511,36,2024-05-16,2024-05-29,2024-05-29,2024-05-29,90,2024-05-28 11:59:28,0.00,0.00,3.07,0.33,2.73
3,FA1114659,50,2024-05-06,2024-05-31,2024-05-31,2024-05-31,50,2024-05-29 14:05:46,8.48,1.06,6.85,1.88,4.97
4,FA1114659,50,2024-05-06,2024-05-31,2024-05-31,2024-05-31,60,2024-05-29 14:06:41,0.02,0.00,0.00,0.00,0.00
5,FA1114659,50,2024-05-06,2024-05-31,2024-05-31,2024-05-31,70,2024-05-29 14:07:28,0.01,0.00,0.00,0.00,0.00
6,FA1114738,1,2024-05-06,2024-05-13,2024-05-13,2024-05-24,50,2024-05-24 14:04:52,0.03,0.00,-4.03,0.50,-4.53
7,FA1114774,250,2024-05-28,2024-06-10,2024-06-10,2024-06-17,22,2024-05-27 12:33:53,14.56,1.82,16.88,0.00,16.88
8,FA1114776,20,2024-05-14,2024-05-21,2024-05-21,2024-05-21,30,2024-05-21 11:39:21,0.01,0.00,0.00,0.00,0.00
9,FA1114776,20,2024-05-14,2024-05-21,2024-05-21,2024-05-21,40,2024-05-21 11:39:47,0.01,0.00,1.70,0.38,1.32

#### Dateninfos

In [ ]:
df_merged.describe(include='all')

,FANummer,Menge,Startdatum,Enddatum,Fälligkeitsdatum,Fertigstellungsdatum,OperationNo,Logdatum,DurchlaufszeitIst(h),DurchlaufszeitIst(t),Rüst-Bearbeitungszeit(h),Rüstzeit(h),Bearbeitungszeit(h)
count,2897,2897.000000,2897,2897,2897,2897,2897.000000,2897,2897.000000,2897.000000,2897.000000,2897.000000,2897.000000
unique,1468,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,FA1116759,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,29.617881,2024-11-07 17:30:18.018640128,2024-11-15 05:21:06.275457280,2024-11-15 05:40:29.409734400,2024-11-19 07:17:25.081118464,74.161892,2024-11-12 21:43:25.942008832,10.848816,1.355830,1.291878,0.323738,0.968488
min,NaN,1.000000,2023-12-15 00:00:00,2024-01-18 00:00:00,2024-01-18 00:00:00,2024-05-21 00:00:00,10.000000,2024-05-21 11:39:03,0.000000,0.000000,-16.800000,-1.670000,-16.800000
25%,NaN,2.000000,2024-08-15 00:00:00,2024-08-21 00:00:00,2024-08-21 00:00:00,2024-08-23 00:00:00,20.000000,2024-08-16 07:57:38,0.010000,0.000000,0.320000,0.120000,0.050000
50%,NaN,10.000000,2024-11-04 00:00:00,2024-11-12 00:00:00,2024-11-12 00:00:00,2024-11-19 00:00:00,30.000000,2024-11-08 15:08:39,4.270000,0.530000,0.580000,0.300000,0.250000
75%,NaN,25.000000,2025-02-06 00:00:00,2025-02-12 00:00:00,2025-02-12 00:00:00,2025-02-13 00:00:00,40.000000,2025-02-11 12:36:00,16.000000,2.000000,1.270000,0.420000,0.830000
max,NaN,581.000000,2025-05-15 00:00:00,2025-05-19 00:00:00,2025-05-19 00:00:00,2025-05-21 00:00:00,5000.000000,2025-05-16 11:48:25,272.000000,34.000000,25.030000,5.880000,24.030000
std,NaN,64.978922,NaN,NaN,NaN,NaN,240.291904,NaN,18.051125,2.256516,2.515336,0.331333,2.405681

#### Kontrolle keine Null values

In [ ]:
df_merged.isnull().sum()

FANummer                    0
Menge                       0
Startdatum                  0
Enddatum                    0
Fälligkeitsdatum            0
Fertigstellungsdatum        0
OperationNo                 0
Logdatum                    0
DurchlaufszeitIst(h)        0
DurchlaufszeitIst(t)        0
Rüst-Bearbeitungszeit(h)    0
Rüstzeit(h)                 0
Bearbeitungszeit(h)         0
dtype: int64

#### Correlation und Covarianz ausgeben

In [ ]:
cols_merged = [
    'Menge',
    'Startdatum',
    'Enddatum',
    'Fälligkeitsdatum',
    'Fertigstellungsdatum',
    'Logdatum',
    'DurchlaufszeitIst(h)',
    'DurchlaufszeitIst(t)',
    'Rüst-Bearbeitungszeit(h)',
    'Rüstzeit(h)',
    'Bearbeitungszeit(h)'
]

corr_matrix = df_merged[cols_merged].corr()
cov_matrix  = df_merged[cols_merged].cov()

print("Korrelationsmatrix:")
display(corr_matrix.round(3))
print("\nKovarianzmatrix:")
display(cov_matrix.round(3))

Korrelationsmatrix:

,Menge,Startdatum,Enddatum,Fälligkeitsdatum,Fertigstellungsdatum,Logdatum,DurchlaufszeitIst(h),DurchlaufszeitIst(t),Rüst-Bearbeitungszeit(h),Rüstzeit(h),Bearbeitungszeit(h)
Menge,1.000,-0.029,-0.006,-0.006,-0.001,-0.011,0.133,0.133,0.703,0.065,0.726
Startdatum,-0.029,1.000,0.989,0.989,0.984,0.987,0.035,0.035,-0.026,-0.032,-0.023
Enddatum,-0.006,0.989,1.000,1.000,0.996,0.996,0.045,0.045,-0.005,-0.020,-0.002
Fälligkeitsdatum,-0.006,0.989,1.000,1.000,0.996,0.996,0.045,0.045,-0.005,-0.020,-0.002
Fertigstellungsdatum,-0.001,0.984,0.996,0.996,1.000,0.997,0.051,0.051,-0.001,-0.018,0.001
Logdatum,-0.011,0.987,0.996,0.996,0.997,1.000,0.048,0.048,-0.011,-0.021,-0.008
DurchlaufszeitIst(h),0.133,0.035,0.045,0.045,0.051,0.048,1.000,1.000,0.269,0.209,0.252
DurchlaufszeitIst(t),0.133,0.035,0.045,0.045,0.051,0.048,1.000,1.000,0.269,0.209,0.252
Rüst-Bearbeitungszeit(h),0.703,-0.026,-0.005,-0.005,-0.001,-0.011,0.269,0.269,1.000,0.389,0.992
Rüstzeit(h),0.065,-0.032,-0.020,-0.020,-0.018,-0.021,0.209,0.209,0.389,1.000,0.269
Bearbeitungszeit(h),0.726,-0.023,-0.002,-0.002,0.001,-0.008,0.252,0.252,0.992,0.269,1.000

Kovarianzmatrix:

,Menge,Startdatum,Enddatum,Fälligkeitsdatum,Fertigstellungsdatum,Logdatum,DurchlaufszeitIst(h),DurchlaufszeitIst(t),Rüst-Bearbeitungszeit(h),Rüstzeit(h),Bearbeitungszeit(h)
Menge,4.222260e+03,-1.693707e+16,-3.528174e+15,-3.464838e+15,-5.477490e+14,-6.163876e+15,1.564230e+02,1.955100e+01,1.149530e+02,1.400000e+00,1.135580e+02
Startdatum,-1.693707e+16,7.955267e+31,7.737659e+31,7.736616e+31,7.740118e+31,7.738454e+31,5.691849e+15,7.114611e+14,-5.867472e+14,-9.391671e+13,-4.935542e+14
Enddatum,-3.528174e+15,7.737659e+31,7.700005e+31,7.698940e+31,7.705383e+31,7.687795e+31,7.161019e+15,8.951808e+14,-1.000657e+14,-5.824407e+13,-4.262788e+13
Fälligkeitsdatum,-3.464838e+15,7.736616e+31,7.698940e+31,7.697903e+31,7.704322e+31,7.686733e+31,7.159741e+15,8.950210e+14,-9.973968e+13,-5.816309e+13,-4.238178e+13
Fertigstellungsdatum,-5.477490e+14,7.740118e+31,7.705383e+31,7.704322e+31,7.780128e+31,7.736363e+31,8.060939e+15,1.007679e+15,-2.832949e+13,-5.396091e+13,2.477408e+13
Logdatum,-6.163876e+15,7.738454e+31,7.687795e+31,7.686733e+31,7.736363e+31,7.734710e+31,7.647124e+15,9.558981e+14,-2.327246e+14,-6.264036e+13,-1.709516e+14
DurchlaufszeitIst(h),1.564230e+02,5.691849e+15,7.161019e+15,7.159741e+15,8.060939e+15,7.647124e+15,3.258430e+02,4.073300e+01,1.221600e+01,1.252000e+00,1.096000e+01
DurchlaufszeitIst(t),1.955100e+01,7.114611e+14,8.951808e+14,8.950210e+14,1.007679e+15,9.558981e+14,4.073300e+01,5.092000e+00,1.527000e+00,1.570000e-01,1.370000e+00
Rüst-Bearbeitungszeit(h),1.149530e+02,-5.867472e+14,-1.000657e+14,-9.973968e+13,-2.832949e+13,-2.327246e+14,1.221600e+01,1.527000e+00,6.327000e+00,3.240000e-01,6.002000e+00
Rüstzeit(h),1.400000e+00,-9.391671e+13,-5.824407e+13,-5.816309e+13,-5.396091e+13,-6.264036e+13,1.252000e+00,1.570000e-01,3.240000e-01,1.100000e-01,2.140000e-01
Bearbeitungszeit(h),1.135580e+02,-4.935542e+14,-4.262788e+13,-4.238178e+13,2.477408e+13,-1.709516e+14,1.096000e+01,1.370000e+00,6.002000e+00,2.140000e-01,5.787000e+00

#### Datenset speichern

In [ ]:
output_xlsx = r"RealDataMerged/mergedBased.xlsx"
df_merged.to_excel(output_xlsx, index=False)